### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by mvinyard** [dynverse/dyngen#13] opened 2019-09-13 15:01 UTC
Hi there, 

I have installed Dynverse properly to my knowledge, however the example object, `model` fails at this stage (pictured). Any help would be appreciated. 
![Screen Shot 2019-09-13 at 11 00 22 AM](https://user-images.githubusercontent.com/47393421/64872775-c4726780-d615-11e9-9d33-fe80f523f372.png)

**Comment by rcannood** [comment] 2019-09-13 15:25
Hello Michael,

This is caused by a recent update from `ggraph` which deprecated some arguments. I just merged the devel branch into master. Could you reinstall dyngen and see if this solves your problem?

Robrecht

**Comment by rcannood** [comment] 2020-08-17 08:00
The issue should be solved.

**Closed by rcannood** 2020-08-17 08:00 UTC
